server:
  port: 8079

spring:
  application:
    name: spring-batch-poc
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/sport_data?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

almanac:
  api:
    base-url: ${ALMANAC_URL}
    username: ${ALMANAC_API_USERNAME:example}
    password: ${ALMANAC_PASSWORD}

sportradar:
  nfl:
    v7:
      key: ${SPORTRADAR_TRIAL_KEY}
      accessLevel: trial
